# Generated by Django 4.2.7 on 2026-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workflow_mixin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditengagement',
            name='workflow_plan_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the workflow plan in Work Orchestration Service', null=True),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='workflow_plan_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the workflow plan in Work Orchestration Service', null=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='workflow_plan_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the workflow plan in Work Orchestration Service', null=True),
        ),
        migrations.AlterField(
            model_name='audituniverse',
            name='workflow_plan_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the workflow plan in Work Orchestration Service', null=True),
        ),
    ]
