# Generated by Django 4.2.7 on 2026-02-27 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditengagement_workflow_plan_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('reference_number', models.CharField(help_text='Unique meeting reference (auto-generated)', max_length=100, unique=True)),
                ('meeting_type', models.CharField(choices=[('entry', 'Entry Meeting'), ('pre_exit', 'Pre-Exit Meeting'), ('audit_team', 'Audit Team Meeting'), ('exit', 'Exit Meeting')], help_text='Type of meeting', max_length=20)),
                ('title', models.CharField(help_text='Meeting title', max_length=500)),
                ('meeting_date', models.DateTimeField(help_text='Scheduled date and time of the meeting')),
                ('location', models.CharField(blank=True, default='', help_text='Meeting venue or location', max_length=300)),
                ('attendees', models.JSONField(blank=True, default=list, help_text='List of meeting attendees with roles and attendance status')),
                ('agenda', models.TextField(blank=True, default='', help_text='Meeting agenda items')),
                ('minutes', models.TextField(blank=True, default='', help_text='Meeting minutes / proceedings')),
                ('key_discussions', models.TextField(blank=True, default='', help_text='Summary of key discussion points')),
                ('action_items', models.JSONField(blank=True, default=list, help_text='Action items arising from the meeting')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', help_text='Current meeting status', max_length=20)),
                ('organized_by', models.UUIDField(help_text='User ID of the meeting organizer (typically LA)')),
                ('document_id', models.UUIDField(blank=True, help_text='Minutes document reference from Document Records Service', null=True)),
                ('engagement', models.ForeignKey(help_text='Parent audit engagement', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.auditengagement')),
            ],
            options={
                'verbose_name': 'Audit Meeting',
                'verbose_name_plural': 'Audit Meetings',
                'db_table': 'grc_audit_meeting',
                'ordering': ['-meeting_date'],
            },
        ),
    ]
