# Generated by Django 4.2.7 on 2026-02-27 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditmeeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyAuditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('workflow_plan_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of the workflow plan in Work Orchestration Service', null=True)),
                ('workflow_stage', models.CharField(blank=True, default='', help_text='Current stage name in Work Orchestration Service', max_length=255)),
                ('workflow_stage_id', models.UUIDField(blank=True, help_text='UUID of the current stage in Work Orchestration Service', null=True)),
                ('workflow_started_at', models.DateTimeField(blank=True, help_text='When the workflow plan was started', null=True)),
                ('workflow_completed_at', models.DateTimeField(blank=True, help_text='When the workflow plan reached a terminal state', null=True)),
                ('reference_number', models.CharField(help_text='Unique report reference — QTR-{FY}-Q{num}-{seq} (auto-generated)', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Report title', max_length=500)),
                ('reporting_period_start', models.DateField(help_text='Start date of the reporting period')),
                ('reporting_period_end', models.DateField(help_text='End date of the reporting period')),
                ('executive_summary', models.TextField(blank=True, default='', help_text='High-level summary for senior management / committee')),
                ('audit_activities_summary', models.TextField(blank=True, default='', help_text='Summary of all audit activities conducted during the quarter')),
                ('findings_overview', models.TextField(blank=True, default='', help_text='Narrative overview of key findings across all engagements')),
                ('risk_themes', models.JSONField(blank=True, default=list, help_text='Identified risk themes/trends — [{"theme": "...", "severity": "..."}]')),
                ('recommendations_overview', models.TextField(blank=True, default='', help_text='Aggregated recommendations narrative')),
                ('implementation_status_summary', models.TextField(blank=True, default='', help_text='Status of prior recommendations implementation')),
                ('key_achievements', models.TextField(blank=True, default='', help_text='Significant achievements and milestones during the quarter')),
                ('challenges_and_constraints', models.TextField(blank=True, default='', help_text='Challenges, resource constraints, or obstacles encountered')),
                ('next_quarter_plan', models.TextField(blank=True, default='', help_text='Planned audit activities for the next quarter')),
                ('conclusion', models.TextField(blank=True, default='', help_text='Overall conclusion and audit opinion for the quarter')),
                ('management_notes', models.TextField(blank=True, default='', help_text='Management deliberation notes added during management_review stage')),
                ('committee_notes', models.TextField(blank=True, default='', help_text='Audit Committee review notes added during committee_review stage')),
                ('total_engagements', models.IntegerField(default=0, help_text='Total number of audit engagements covered this quarter')),
                ('total_findings', models.IntegerField(default=0, help_text='Total number of audit findings across all engagements')),
                ('critical_findings', models.IntegerField(default=0, help_text='Number of critical / high-severity findings')),
                ('total_recommendations', models.IntegerField(default=0, help_text='Total recommendations issued across all engagements')),
                ('implementation_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of prior recommendations implemented (0–100)', max_digits=5)),
                ('planned_vs_actual', models.JSONField(blank=True, default=dict, help_text='Planned vs actual audit activities summary')),
                ('findings_summary', models.JSONField(blank=True, default=list, help_text='Aggregated findings summary across all engagements')),
                ('recommendations_summary', models.JSONField(blank=True, default=list, help_text='Aggregated recommendations implementation status')),
                ('resource_utilization', models.JSONField(blank=True, default=dict, help_text='Staffing days used, budget utilization summary')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('cia_review', 'CIA Review'), ('management_review', 'Management Review'), ('committee_review', 'Audit Committee Review'), ('improvement_required', 'Improvement Required'), ('approved', 'Approved'), ('submitted_to_commission', 'Submitted to Commission')], db_index=True, default='draft', help_text='Current workflow status of the quarterly report', max_length=30)),
                ('instructed_by', models.UUIDField(blank=True, help_text='User ID of the CIA who instructed preparation of this report', null=True)),
                ('prepared_by', models.UUIDField(help_text='User ID of the report preparer (typically CIA or senior auditor)')),
                ('reviewed_by', models.UUIDField(blank=True, help_text='User ID of the reviewer', null=True)),
                ('approved_by', models.UUIDField(blank=True, help_text='User ID of the approver', null=True)),
                ('approval_date', models.DateTimeField(blank=True, help_text='Timestamp when the report was formally approved', null=True)),
                ('submitted_to', models.CharField(blank=True, default='', help_text='Name / title of the committee or authority the report was submitted to', max_length=300)),
                ('submission_date', models.DateField(blank=True, help_text='Date the report was formally submitted', null=True)),
                ('document_id', models.UUIDField(blank=True, help_text='Reference to uploaded report document in Document Records Service', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('engagement_reports', models.ManyToManyField(blank=True, help_text='Individual audit reports (from engagements) consolidated in this quarterly report', related_name='quarterly_reports', to='core.auditreport')),
                ('fiscal_year', models.ForeignKey(help_text='Fiscal year this report covers', on_delete=django.db.models.deletion.PROTECT, related_name='quarterly_reports', to='core.fiscalyear')),
                ('quarter', models.ForeignKey(help_text='Fiscal quarter this report covers', on_delete=django.db.models.deletion.PROTECT, related_name='quarterly_reports', to='core.quarter')),
            ],
            options={
                'verbose_name': 'Quarterly Audit Report',
                'verbose_name_plural': 'Quarterly Audit Reports',
                'db_table': 'grc_quarterly_audit_report',
                'ordering': ['-reporting_period_end'],
                'unique_together': {('fiscal_year', 'quarter')},
            },
        ),
    ]
