# Generated by Django 4.2.7 on 2026-02-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quarterlyauditreport_srs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditmeeting',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Audit Meeting', 'verbose_name_plural': 'Audit Meetings'},
        ),
        migrations.RenameField(
            model_name='auditmeeting',
            old_name='document_id',
            new_name='minutes_document_id',
        ),
        migrations.RenameField(
            model_name='auditmeeting',
            old_name='meeting_date',
            new_name='scheduled_date',
        ),
        migrations.AddField(
            model_name='auditmeeting',
            name='actual_date',
            field=models.DateTimeField(blank=True, help_text='Actual date and time the meeting took place', null=True),
        ),
        migrations.AddField(
            model_name='auditmeeting',
            name='attendance_document_id',
            field=models.UUIDField(blank=True, help_text='Attendance sheet document reference from Document Records Service', null=True),
        ),
        migrations.AlterField(
            model_name='auditmeeting',
            name='meeting_type',
            field=models.CharField(choices=[('entry', 'Entry Meeting'), ('pre_exit', 'Pre-Exit Meeting'), ('team', 'Audit Team Meeting'), ('exit', 'Exit Meeting')], help_text='Type of meeting', max_length=20),
        ),
    ]
