# Generated by Django 4.2.7 on 2026-03-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditmemo_riskcontrolmatrix_rcmentry_auditsurvey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementationmonitoring',
            name='auditee_responded_at',
            field=models.DateTimeField(blank=True, help_text='When the auditee submitted their response', null=True),
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='escalated',
            field=models.BooleanField(default=False, help_text='Whether this record has been escalated to CIA'),
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='is_overdue',
            field=models.BooleanField(default=False, help_text='Whether the response deadline has passed without response'),
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the implementation list was shared with auditee', null=True),
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text='Auto-calculated: notification_sent_at + 5 business days', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='auto_overall_rating',
            field=models.ForeignKey(blank=True, help_text='System-calculated overall risk rating based on weighted score', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_overall_assessments', to='core.riskrating'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='auto_residual_rating',
            field=models.ForeignKey(blank=True, help_text='System-calculated residual risk rating', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_residual_assessments', to='core.riskrating'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='calculated_residual_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated residual risk score after control adjustment', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='calculated_weighted_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated weighted risk score', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='rating_overridden',
            field=models.BooleanField(default=False, help_text='Whether the user has manually overridden the auto-calculated rating'),
        ),
        migrations.AddField(
            model_name='riskrating',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weighted score threshold for this rating (exclusive)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='riskrating',
            name='min_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weighted score threshold for this rating (inclusive)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='auditengagement',
            name='engagement_type',
            field=models.CharField(choices=[('planned', 'Planned Engagement'), ('unplanned', 'Unplanned Engagement'), ('special_investigation', 'Special Investigation'), ('follow_up', 'Follow-up Engagement')], default='planned', help_text='Type of audit engagement', max_length=25),
        ),
    ]
