# Generated by Django 4.2.7 on 2026-03-05 12:13

from django.db import migrations


def rename_ad_hoc_to_unplanned(apps, schema_editor):
    """Rename existing 'ad_hoc' engagement_type values to 'unplanned'."""
    AuditEngagement = apps.get_model('core', 'AuditEngagement')
    count = AuditEngagement.objects.filter(engagement_type='ad_hoc').update(
        engagement_type='unplanned'
    )
    if count:
        print(f"  Renamed {count} engagement(s) from 'ad_hoc' to 'unplanned'")


def reverse_rename(apps, schema_editor):
    """Reverse: rename 'unplanned' back to 'ad_hoc'."""
    AuditEngagement = apps.get_model('core', 'AuditEngagement')
    AuditEngagement.objects.filter(engagement_type='unplanned').update(
        engagement_type='ad_hoc'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_phase_b_risk_scoring_and_monitoring'),
    ]

    operations = [
        migrations.RunPython(rename_ad_hoc_to_unplanned, reverse_rename),
    ]
