# Generated by Django 4.2.7 on 2026-03-05 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_ad_hoc_to_unplanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='overall_risk_rating',
            field=models.ForeignKey(blank=True, help_text='Overall risk rating from lookup table (auto-populated by scoring)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overall_assessments', to='core.riskrating'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='residual_risk_rating',
            field=models.ForeignKey(blank=True, help_text='Post-control risk rating (auto-populated by scoring)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residual_assessments', to='core.riskrating'),
        ),
    ]
