# Generated by Django 4.2.7 on 2026-03-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_phase_b_fix_nullable_rating_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditmemo',
            name='document_id',
            field=models.UUIDField(blank=True, help_text='DRS document UUID — set when memo is uploaded as a PDF document', null=True),
        ),
        migrations.AddField(
            model_name='auditmemo',
            name='stamped_document_url',
            field=models.URLField(blank=True, help_text='URL to approved PDF with embedded CIA signature and QR code (GAP 9)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='document_id',
            field=models.UUIDField(blank=True, help_text='DRS document UUID — set when program is uploaded as a PDF document', null=True),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='stamped_document_url',
            field=models.URLField(blank=True, help_text='URL to approved PDF with embedded CIA signature and QR code (GAP 9)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='stamped_document_url',
            field=models.URLField(blank=True, help_text='URL to approved PDF with embedded CIA signature and QR code (GAP 9)', max_length=500, null=True),
        ),
    ]
