# Generated by Django 4.2.7 on 2026-03-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auditmemo_document_id_auditmemo_stamped_document_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationofindependence',
            name='document_id',
            field=models.UUIDField(blank=True, help_text='DRS document UUID for the signed declaration PDF (GAP 9)', null=True),
        ),
        migrations.AddField(
            model_name='declarationofindependence',
            name='stamped_document_url',
            field=models.URLField(blank=True, help_text='URL to the signed + QR-stamped declaration PDF (GAP 9)', max_length=500, null=True),
        ),
    ]
