# Generated by Django 4.2.7 on 2026-03-07 12:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_declaration_stamp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('workflow_plan_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of the workflow plan in Work Orchestration Service', null=True)),
                ('workflow_stage', models.CharField(blank=True, default='', help_text='Current stage name in Work Orchestration Service', max_length=255)),
                ('workflow_stage_id', models.UUIDField(blank=True, help_text='UUID of the current stage in Work Orchestration Service', null=True)),
                ('workflow_started_at', models.DateTimeField(blank=True, help_text='When the workflow plan was started', null=True)),
                ('workflow_completed_at', models.DateTimeField(blank=True, help_text='When the workflow plan reached a terminal state', null=True)),
                ('reference_number', models.CharField(help_text='Unique EN reference (auto: EN-{engagement_ref})', max_length=100, unique=True)),
                ('notification_date', models.DateField(blank=True, help_text='Date the notification is formally issued', null=True)),
                ('audit_period_start', models.DateField(help_text='Start of the audit period stated in the EN')),
                ('audit_period_end', models.DateField(help_text='End of the audit period stated in the EN')),
                ('audit_team_snapshot', models.JSONField(blank=True, default=list, help_text='Audit team composition at time of notification. Format: [{"user_id": "uuid", "role": "lead_auditor|team_member", "name": "Full Name"}]')),
                ('scope_summary', models.TextField(blank=True, default='', help_text='Summary of audit scope to include in the EN document')),
                ('prepared_by', models.UUIDField(help_text='LA who prepared the EN (user ID from IAM)')),
                ('approved_by_cia', models.UUIDField(blank=True, help_text='CIA who approved the EN (user ID from IAM)', null=True)),
                ('cia_approval_date', models.DateTimeField(blank=True, help_text='When the CIA approved', null=True)),
                ('transmitted_at', models.DateTimeField(blank=True, help_text='When the EN was transmitted to the auditable area', null=True)),
                ('document_id', models.UUIDField(blank=True, help_text='DRS document UUID (set when EN is uploaded as PDF)', null=True)),
                ('stamped_document_url', models.URLField(blank=True, help_text='URL to approved PDF with embedded CIA signature and QR code (GAP 9)', max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under CIA Review'), ('approved', 'Approved'), ('transmitted', 'Transmitted to Auditable Area')], db_index=True, default='draft', help_text='Current status of the engagement notification', max_length=15)),
                ('audit_engagement', models.OneToOneField(help_text='Engagement this notification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='engagement_notification', to='core.auditengagement')),
                ('audit_program', models.ForeignKey(blank=True, help_text='Linked Audit Program (optional — used to pull scope summary)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_notifications', to='core.auditprogram')),
            ],
            options={
                'verbose_name': 'Engagement Notification',
                'verbose_name_plural': 'Engagement Notifications',
                'db_table': 'grc_engagement_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
