# Generated by Django 4.2.7 on 2026-03-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auditee_follow_up_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationmonitoring',
            name='auditee_responded_at',
            field=models.DateTimeField(blank=True, help_text='When the auditee last submitted a response (mirrored from current cycle)', null=True),
        ),
        migrations.AlterField(
            model_name='implementationmonitoring',
            name='is_overdue',
            field=models.BooleanField(default=False, help_text="Whether the current cycle's response deadline has passed without response"),
        ),
        migrations.AlterField(
            model_name='implementationmonitoring',
            name='latest_progress',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Latest implementation progress % (denormalized from most-recent follow-up response)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='implementationmonitoring',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the auditee was last notified (mirrored from current cycle)', null=True),
        ),
        migrations.AlterField(
            model_name='implementationmonitoring',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text='Current cycle deadline (mirrored from current AuditeeFollowUpResponse)', null=True),
        ),
        migrations.AlterField(
            model_name='implementationmonitoring',
            name='reviewed_by',
            field=models.UUIDField(blank=True, help_text='User ID of the most-recent reviewer', null=True),
        ),
        migrations.AlterField(
            model_name='implementationmonitoring',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], db_index=True, default='active', help_text='Monitoring lifecycle status (active → closed when recommendation is fully implemented)', max_length=20),
        ),
    ]
