# Generated by Django 4.2.7 on 2026-03-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auditprogram_audit_scope'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audituniverse',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='audituniverse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('fiscal_year',), name='grc_audit_universe_active_fiscal_year_uniq'),
        ),
    ]
