# Generated by Django 4.2.7 on 2026-03-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_drop_unique_together_add_partial_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditmeeting',
            name='agreed_observations',
            field=models.TextField(blank=True, default='', help_text='Observations agreed upon between auditors and auditee (SRS: Key Info for pre-exit meeting)'),
        ),
        migrations.AddField(
            model_name='auditmeeting',
            name='clarifications',
            field=models.TextField(blank=True, default='', help_text='Issues clarified during pre-exit meeting (SRS: Key Info for pre-exit meeting)'),
        ),
    ]
