# Generated by Django 4.2.7 on 2026-03-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_meeting_clarifications_agreed_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditmeeting',
            name='draft_report_id',
            field=models.UUIDField(blank=True, help_text='UUID of the draft audit report attached to exit meeting notification', null=True),
        ),
        migrations.AddField(
            model_name='auditmeeting',
            name='notification_date',
            field=models.DateTimeField(blank=True, help_text='When the exit meeting notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='auditmeeting',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether exit meeting notification has been sent to auditee'),
        ),
    ]
