# Generated by Django 4.2.7 on 2026-03-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_meeting_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='discussed_at',
            field=models.DateTimeField(blank=True, help_text='When the finding was first marked as discussed with the auditee', null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When the finding was finalized (both responses recorded)', null=True),
        ),
    ]
