# Generated by Django 4.2.7 on 2026-03-19 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_finding_lifecycle_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('code', models.CharField(help_text="Machine-readable identifier (e.g., 'high_court', 'court_of_appeal')", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Full display name of the court level', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional notes for admin reference')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Hierarchy order: lower = lower court (e.g., Magistrate=1, Supreme=5)')),
            ],
            options={
                'verbose_name': 'Court Level',
                'verbose_name_plural': 'Court Levels',
                'db_table': 'grc_court_level',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DirectiveCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('code', models.CharField(help_text="Machine-readable category code (e.g., 'legal_compliance', 'finance')", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the category', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what directives belong in this category')),
            ],
            options={
                'verbose_name': 'Directive Category',
                'verbose_name_plural': 'Directive Categories',
                'db_table': 'grc_directive_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DirectivePriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('code', models.CharField(help_text="Machine-readable code (e.g., 'critical', 'high', 'medium', 'low')", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the priority level', max_length=100)),
                ('color_code', models.CharField(default='#6B7280', help_text="Hex colour for UI badge (e.g., '#DC2626' for Critical)", max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order: lower = higher priority displayed first (Critical=1)')),
            ],
            options={
                'verbose_name': 'Directive Priority',
                'verbose_name_plural': 'Directive Priorities',
                'db_table': 'grc_directive_priority',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LitigationRiskLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('code', models.CharField(help_text="Machine-readable code (e.g., 'high_risk', 'medium_risk', 'low_risk')", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name shown in UI dropdowns', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Criteria for assigning this risk level')),
                ('color_code', models.CharField(default='#6B7280', help_text='Hex colour for UI badge', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order for reports: lower = higher risk')),
            ],
            options={
                'verbose_name': 'Litigation Risk Level',
                'verbose_name_plural': 'Litigation Risk Levels',
                'db_table': 'grc_litigation_risk_level',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LitigationUrgencyLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('code', models.CharField(help_text="Machine-readable code (e.g., 'critical', 'high', 'medium', 'low')", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name shown in UI dropdowns and reports', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Criteria for selecting this urgency level')),
                ('color_code', models.CharField(default='#6B7280', help_text="Hex colour for UI badge (e.g., '#DC2626' for Critical)", max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order: lower = higher urgency (Critical=1, Low=4)')),
            ],
            options={
                'verbose_name': 'Litigation Urgency Level',
                'verbose_name_plural': 'Litigation Urgency Levels',
                'db_table': 'grc_litigation_urgency_level',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('code', models.CharField(help_text="Machine-readable code (e.g., 'physical', 'virtual', 'hybrid')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Physical', 'Virtual', 'Hybrid')", max_length=100)),
                ('requires_venue_link', models.BooleanField(default=False, help_text='Whether this mode requires a virtual meeting link')),
            ],
            options={
                'verbose_name': 'Meeting Mode',
                'verbose_name_plural': 'Meeting Modes',
                'db_table': 'grc_meeting_mode',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('code', models.CharField(help_text="Machine-readable code (e.g., 'ordinary', 'extraordinary', 'special')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Ordinary Meeting')", max_length=100)),
                ('quorum_percentage', models.PositiveSmallIntegerField(default=51, help_text='Minimum percentage of members required for quorum (e.g., 51 = majority, 67 = two-thirds). Used by Meeting.save() to compute quorum threshold.')),
                ('description', models.TextField(blank=True, help_text='Conditions under which this meeting type is convened')),
            ],
            options={
                'verbose_name': 'Meeting Type',
                'verbose_name_plural': 'Meeting Types',
                'db_table': 'grc_meeting_type',
                'ordering': ['name'],
            },
        ),
    ]
