# Generated by Django 4.2.7 on 2026-03-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_legal_entities_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='workflow_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the workflow plan reached a terminal state', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='workflow_plan_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the workflow plan in Work Orchestration Service', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='workflow_stage',
            field=models.CharField(blank=True, default='', help_text='Current stage name in Work Orchestration Service', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='workflow_stage_id',
            field=models.UUIDField(blank=True, help_text='UUID of the current stage in Work Orchestration Service', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='workflow_started_at',
            field=models.DateTimeField(blank=True, help_text='When the workflow plan was started', null=True),
        ),
    ]
