# Generated by Django 4.2.7 on 2026-03-19 13:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_meeting_add_workflow_mixin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('notice_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('issued_date', models.DateField()),
                ('served_date', models.DateField(blank=True, null=True)),
                ('recipient_info', models.JSONField(blank=True, default=dict, help_text='Recipient details')),
                ('document_id', models.UUIDField(blank=True, help_text='Notice document UUID from DRS', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('acknowledged', 'Acknowledged'), ('expired', 'Expired')], db_index=True, default='draft', max_length=20)),
                ('related_case_defendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_notices', to='core.casedefendant')),
                ('related_case_plaintiff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_notices', to='core.caseplaintiff')),
            ],
            options={
                'db_table': 'legal_notice',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='AppealPlaintiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('appeal_date', models.DateField()),
                ('grounds', models.TextField(help_text='Legal grounds for the appeal')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('dismissed', 'Dismissed'), ('upheld', 'Upheld'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('outcome_date', models.DateField(blank=True, null=True)),
                ('document_id', models.UUIDField(blank=True, help_text='Appeal document UUID from DRS', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('court_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appeals_plaintiff', to='core.courtlevel')),
                ('judgment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='core.judgmentplaintiff')),
            ],
            options={
                'db_table': 'legal_appeal_plaintiff',
                'ordering': ['-appeal_date'],
            },
        ),
        migrations.CreateModel(
            name='AppealDefendant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('appeal_date', models.DateField()),
                ('grounds', models.TextField(help_text='Legal grounds for the appeal')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('dismissed', 'Dismissed'), ('upheld', 'Upheld'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('outcome_date', models.DateField(blank=True, null=True)),
                ('document_id', models.UUIDField(blank=True, help_text='Appeal document UUID from DRS', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('court_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appeals_defendant', to='core.courtlevel')),
                ('judgment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='core.judgmentdefendant')),
            ],
            options={
                'db_table': 'legal_appeal_defendant',
                'ordering': ['-appeal_date'],
            },
        ),
    ]
