# Generated by Django 4.2.7 on 2026-03-19 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_legal_appeals_and_notices'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalNoticeCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'grc_legal_notice_counter',
                'unique_together': {('year',)},
            },
        ),
    ]
