# Generated by Django 4.2.7 on 2026-03-20 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_legal_notice_counter'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meetingagenda',
            name='legal_meeting_agenda_active_meeting_submission_uniq',
        ),
        migrations.AddField(
            model_name='meetingagenda',
            name='source_directive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arising_agenda_items', to='core.meetingdirective'),
        ),
        migrations.AlterField(
            model_name='meetingagenda',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agenda_items', to='core.submissionfordetermination'),
        ),
        migrations.AddConstraint(
            model_name='meetingagenda',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('submission__isnull', False)), fields=('meeting', 'submission'), name='legal_meeting_agenda_active_meeting_submission_uniq'),
        ),
        migrations.AddConstraint(
            model_name='meetingagenda',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('source_directive__isnull', False)), fields=('meeting', 'source_directive'), name='legal_meeting_agenda_active_meeting_directive_uniq'),
        ),
    ]
