# Generated by Django 4.2.7 on 2026-03-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_legal_agenda_nullable_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingdefendant',
            name='stamped_document_url',
            field=models.URLField(blank=True, help_text='URL to the stamped PDF served by DRS (GAP-10)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='filingplaintiff',
            name='stamped_document_url',
            field=models.URLField(blank=True, help_text='URL to the stamped PDF served by DRS (GAP-10)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='judgmentdefendant',
            name='stamped_document_url',
            field=models.URLField(blank=True, help_text='URL to the stamped PDF served by DRS (GAP-10)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='judgmentplaintiff',
            name='stamped_document_url',
            field=models.URLField(blank=True, help_text='URL to the stamped PDF served by DRS (GAP-10)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settlementdefendant',
            name='stamped_document_url',
            field=models.URLField(blank=True, help_text='URL to the stamped PDF served by DRS (GAP-10)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settlementplaintiff',
            name='stamped_document_url',
            field=models.URLField(blank=True, help_text='URL to the stamped PDF served by DRS (GAP-10)', max_length=500, null=True),
        ),
    ]
