# Generated by Django 4.2.7 on 2026-03-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_gap10_digital_signature_stamped_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedefendant',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedefendant',
            name='archived_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedefendant',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='caseplaintiff',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseplaintiff',
            name='archived_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseplaintiff',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
