# Generated by Django 4.2.7 on 2026-03-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_risk_management_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformance',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='disputed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmsauditreport',
            name='mrm_directives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsauditreport',
            name='mrm_directives_communicated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmsauditreport',
            name='returned_for_revision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmsauditreport',
            name='rmqam_review_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskassessmentsheet',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmentsheet',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmentsheet',
            name='review_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskassessmentsheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted_to_head', 'Submitted to Head'), ('head_endorsed', 'Head Endorsed'), ('submitted_to_rmqam', 'Submitted to RMQAM'), ('approved', 'Approved'), ('returned_for_rework', 'Returned for Rework')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='status',
            field=models.CharField(choices=[('raised', 'Raised'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('disputed', 'Disputed'), ('withdrawn', 'Withdrawn')], db_index=True, default='raised', max_length=20),
        ),
        migrations.AlterField(
            model_name='qmsauditreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('tl_signed', 'TL Signed'), ('auditee_acknowledged', 'Auditee Acknowledged'), ('finalised', 'Finalised'), ('submitted_to_rmqam', 'Submitted to RMQAM'), ('returned_for_revision', 'Returned for Revision'), ('presented_at_mrm', 'Presented at MRM'), ('directives_received', 'Directives Received'), ('submitted_to_audit_committee', 'Submitted to Audit Committee'), ('audit_committee_reviewed', 'Audit Committee Reviewed'), ('adopted_by_commission', 'Adopted by Commission')], db_index=True, default='draft', max_length=35),
        ),
    ]
