# Generated by Django 4.2.7 on 2026-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_phase1_ras_qms_nc_gaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalriskregister',
            name='directors_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionalriskregister',
            name='distributed_to_directorates_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionalriskregister',
            name='distribution_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='institutionalriskregister',
            name='rcs_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionalriskregister',
            name='workshop_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionalriskregister',
            name='workshop_venue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='risktreatmentactionplan',
            name='distributed_to_directorates_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risktreatmentactionplan',
            name='distribution_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rtapitem',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtapitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtapitem',
            name='review_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rtapitem',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('returned_for_rework', 'Returned for Rework')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='rtapquarterlyupdate',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('returned_for_rework', 'Returned for Rework')], db_index=True, default='not_started', max_length=20),
        ),
    ]
