# Generated by Django 4.2.7 on 2026-03-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_phase2_rtap_irr_distribution_gaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformance',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qatrainingattendee',
            name='exam_attempt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qatrainingattendee',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qatrainingattendee',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='qatrainingattendee',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qatrainingsession',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text='GAP-23: Reason for rejecting the training session'),
        ),
        migrations.AddField(
            model_name='qualityauditor',
            name='experience_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qualityauditor',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='riskmeeting',
            name='meeting_type',
            field=models.CharField(choices=[('risk_discussion', 'Risk Discussion'), ('workshop', 'Workshop'), ('brainstorming', 'Brainstorming'), ('institutional_workshop', 'Institutional Workshop'), ('awareness_session', 'Awareness Session'), ('management_review', 'Management Review')], max_length=30),
        ),
    ]
