# Generated by Django 4.2.7 on 2026-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_phase3_qa_nc_meeting_gaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedefendant',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caseplaintiff',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='meeting_number_format',
            field=models.CharField(choices=[('sequential', 'Sequential'), ('financial_year', 'Financial Year')], default='sequential', max_length=20),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='meeting_number_prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='litigationdirective',
            name='requires_dg_approval_for_closure',
            field=models.BooleanField(default=False, help_text='When True, closure must pass through DG approval before being finalised.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasklitigation',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='True when the task was created programmatically (e.g. appeal deadline, filing review).'),
        ),
        migrations.AlterField(
            model_name='litigationdirective',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_dg_approval', 'Pending DG Approval'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
    ]
