# Generated by Django 4.2.7 on 2026-03-24 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_legal_phase3_model_additions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskSector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Risk Sector',
                'verbose_name_plural': 'Risk Sectors',
                'db_table': 'grc_risk_sector',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Strategic Objective',
                'verbose_name_plural': 'Strategic Objectives',
                'db_table': 'grc_strategic_objective',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
