# Generated by Django 4.2.7 on 2026-03-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_risksector_strategicobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessmentsheet',
            name='causes',
            field=models.TextField(blank=True, help_text='Root causes of the risk'),
        ),
        migrations.AddField(
            model_name='riskassessmentsheet',
            name='consequences',
            field=models.TextField(blank=True, help_text='Consequences if risk materialises'),
        ),
        migrations.AddField(
            model_name='riskassessmentsheet',
            name='risk_indicator',
            field=models.CharField(blank=True, help_text='Key risk indicator', max_length=255),
        ),
        migrations.AddField(
            model_name='riskassessmentsheet',
            name='risk_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_sheets', to='core.risksector'),
        ),
        migrations.AddField(
            model_name='riskassessmentsheet',
            name='strategic_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_sheets', to='core.strategicobjective'),
        ),
        migrations.AddField(
            model_name='riskassessmentsheet',
            name='supporting_owners',
            field=models.JSONField(default=list, help_text='List of supporting risk owner IAM user UUIDs'),
        ),
        migrations.AddField(
            model_name='rtapitem',
            name='corrective_effectiveness',
            field=models.CharField(blank=True, choices=[('effective', 'Effective'), ('partially_effective', 'Partially Effective'), ('not_effective', 'Not Effective')], help_text='Effectiveness of corrective controls', max_length=30),
        ),
        migrations.AddField(
            model_name='rtapitem',
            name='corrective_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Corrective control effectiveness rating %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rtapitem',
            name='kci',
            field=models.TextField(blank=True, help_text='Key Control Indicator'),
        ),
        migrations.AddField(
            model_name='rtapitem',
            name='preventive_effectiveness',
            field=models.CharField(blank=True, choices=[('effective', 'Effective'), ('partially_effective', 'Partially Effective'), ('not_effective', 'Not Effective')], help_text='Effectiveness of preventive controls', max_length=30),
        ),
        migrations.AddField(
            model_name='rtapitem',
            name='preventive_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preventive control effectiveness rating %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rtapitem',
            name='resources_required',
            field=models.TextField(blank=True, help_text='Resources required for treatment'),
        ),
    ]
