# Generated by Django 4.2.7 on 2026-03-24 12:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_phase1_ras_rtap_field_enrichment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('org_unit_id', models.UUIDField(blank=True, help_text='Target org unit UUID (null = institution-wide)', null=True)),
                ('created_by_user', models.UUIDField(help_text='RMQAM/RMO user UUID who created the survey')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_surveys', to='core.fiscalyear')),
            ],
            options={
                'db_table': 'grc_risk_survey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activityreport',
            name='dg_noted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='dg_noted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='dg_noted_by',
            field=models.UUIDField(blank=True, help_text='DG user UUID who noted this report', null=True),
        ),
        migrations.AddField(
            model_name='qualityauditor',
            name='nomination_status',
            field=models.CharField(choices=[('active', 'Active'), ('replacement_needed', 'Replacement Needed'), ('replaced', 'Replaced')], db_index=True, default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='risklevel',
            name='is_institutional_threshold',
            field=models.BooleanField(default=False, help_text='If True, risks at or above this level qualify for the Institutional Risk Register'),
        ),
        migrations.AlterField(
            model_name='riskmeeting',
            name='meeting_type',
            field=models.CharField(choices=[('risk_discussion', 'Risk Discussion'), ('workshop', 'Workshop'), ('brainstorming', 'Brainstorming'), ('institutional_workshop', 'Institutional Workshop'), ('awareness_session', 'Awareness Session'), ('management_review', 'Management Review'), ('interview', 'Interview')], max_length=30),
        ),
        migrations.CreateModel(
            name='RiskSurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('rating', 'Rating (1-5)'), ('yes_no', 'Yes / No'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('question_text', models.TextField()),
                ('choices', models.JSONField(default=list, help_text='Options for multiple_choice type')),
                ('sort_order', models.IntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.risksurvey')),
            ],
            options={
                'db_table': 'grc_risk_survey_question',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RiskKnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('source_type', models.CharField(choices=[('lesson_learned', 'Lesson Learned'), ('audit_finding', 'Audit Finding'), ('industry_best_practice', 'Industry Best Practice'), ('external_report', 'External Report')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('document_id', models.UUIDField(blank=True, help_text='DRS document UUID for supporting evidence', null=True)),
                ('tags', models.JSONField(default=list, help_text='Searchable keyword tags')),
                ('contributed_by', models.UUIDField(help_text='IAM user UUID who contributed this entry')),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_base_entries', to='core.fiscalyear')),
            ],
            options={
                'db_table': 'grc_risk_knowledge_base',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskSurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='User ID from IAM service who created this record')),
                ('modified_by', models.UUIDField(blank=True, help_text='User ID from IAM service who last modified this record', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active and available for use')),
                ('respondent_id', models.UUIDField(db_index=True, help_text='IAM user UUID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(default=list, help_text='[{"question_id": "uuid", "answer": "..."}]')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.risksurvey')),
            ],
            options={
                'db_table': 'grc_risk_survey_response',
                'ordering': ['-created_at'],
                'unique_together': {('survey', 'respondent_id')},
            },
        ),
    ]
