# Generated by Django 4.2.7 on 2026-03-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_risksurvey_activityreport_dg_noted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedefendant',
            name='case_folder_url',
            field=models.URLField(blank=True, help_text='URL to the DRS case folder', max_length=500),
        ),
        migrations.AddField(
            model_name='caseplaintiff',
            name='case_folder_url',
            field=models.URLField(blank=True, help_text='URL to the DRS case folder', max_length=500),
        ),
    ]
