# Generated by Django 4.2.7 on 2026-03-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_legal_case_folder_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsedefendant',
            name='response_type',
            field=models.CharField(choices=[('preliminary_objections', 'Preliminary Objections'), ('counter_claim', 'Counter Claim'), ('reply_to_defence', 'Reply to Defence'), ('response_to_ruling', 'Response to Ruling'), ('other', 'Other')], max_length=30),
        ),
    ]
